[workspace]
resolver = "3"
members = [
  "crates/*"
]
exclude = [
  "target/"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["nasccped <pdbt.contact@gmail.com>"]
description = "Simple project manager for simple java apps"
repository = "https://github.com/nasccped/jsmoke"
keywords = ["java", "project manager", "cli"]
categories = ["command-line-utilities"]
exclude = [
  "target/",
  ".git/",
  ".gitignore"
]

# this is intended to works (since each module contains it own README
# file)
readme = "README.md"

[workspace.dependencies]
jsmoke_application = "0.1.0"
jsmoke_cli = "0.1.0"
jsmoke_utils = "0.1.0"
