[workspace]
resolver = "3"
members = [
  "crates/*"
]
exclude = [
  "target/"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["nasccped <pdbt.contact@gmail.com>"]
description = "Simple project manager for simple java apps"
repository = "https://github.com/nasccped/jsmoke"
keywords = ["java", "project-manager", "cli"]
categories = ["command-line-utilities"]
exclude = [
  "target/",
  ".git/",
  ".gitignore"
]

[workspace.dependencies]
# local crates
jsmoke_application = "0.1.0"
jsmoke_cli = "0.1.0"
jsmoke_utils = "0.1.0"
# global dependencies
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
thiserror = "2.0.17"
